### ISSUE TITLE
Ninjarjar don't work

### ISSUE THREAD

**Issue by mabrilG** [sorgelig/ZX_Spectrum-128K_MIST#22]
Ninjarjar! game from Mojon Twins, don't start when the load finish. I try serveral version with the same result.
Thanks.

**Comment by xolod79** [comment]
Hi, I did not find such a game on worldofspectrum.org. give me a link.

**Comment by gyurco** [comment]
I've tried this game last year, just didn't comment here. Worked for me.

**Comment by mabrilG** [comment]
In the last release the game don't finish loading the tap.
You can download it from the author's page:
http://www.mojontwins.com/juegos_mojonos/ninjajar/

**Comment by sorgelig** [comment]
tried this link: http://www.mojontwins.com/juegos/mojon-twins--ninjajar-eng-v1.1.tap
Loaded from 128K menu "Tape Loader" without problem.

**Comment by xolod79** [comment]
I agree, work normal.

**Comment by mabrilG** [comment]
I'm sorry, I had not tried the English version, that works.

The Spanish version and ULA+ does not work.
http://www.mojontwins.com/juegos/mojon-twins--ninjajar-esp-v1.1.tap

The problem has to be theirs, I will contact them to fix it.
Thanks!

**Comment by sorgelig** [comment]
Spanish version has problem in Turbo mode TAP loading.
However you can load it in normal/fast mode - it works. See the readme about different tape loading modes.

**Comment by mabrilG** [comment]
Thanks Sorgelig, without Turbo mode it works.
I already know the different tape loading modes, but I thought Turbo mode always worked.

Many thanks to all for the help.

**Comment by sorgelig** [comment]
Turbo mode is a hack with specific routines interception. This not always works (and will never be) as some games use non-standard calls or even process the tape internally.
