### ISSUE TITLE
no display on VGA monitor

### ISSUE THREAD

**Issue by gorans** [sorgelig/ZX_Spectrum-128K_MIST#3]
There is no picture displayed (out of range). Tried three monitors (Vivitron CRT, Syncmaster 192v and TV with VGA). All other MIST cores are working. Old spectrum cores are also working. There is scandoubler_disable=0 in mist.ini.

Best regards,
Goran

**Comment by sorgelig** [comment]
Unfortunately, i don't have monitor supporting VGA 50Hz. I only can test with capture card which is working with ZX Spectrum core in scandoubler mode.
Maybe @harbaum can check with his monitor and tell what's the problem.

I guess Vertical sync frequency is too low. If it's true then i cannot do anything here. Actually 50Hz VGA is already beyond of VGA standard.

**Comment by gorans** [comment]
I think the same but all other PAL cores are working so that's why I posted this Issue.

**Comment by sorgelig** [comment]
May be core simply doesn't start? Can you try TV mode with scan doubler disabled?
Make sure you've put latest spectrum.rom into root of SD card.

**Comment by gorans** [comment]
Hi,

it was working on the Sony CRT that I sold. That one was displaying all freqs correctly. I tried to connect the TV via VGA->RGB component cable but it’s not working at all, so I can’t double check Speccy core. 

Best regards,
Goran

**Comment by gorans** [comment]
Update:
I have saved default settings to Pentagon video, which is not working. After resetting video type to ZX, i have picture.

**Comment by sorgelig** [comment]
It just proves that your monitor cannot handle all ZX core VSyncs.
In ZX mode - there are 311 and 312 lines. In Pentagon mode there are 320 lines, so vertical sync has lower frequency. ~48hz.

**Comment by sorgelig** [comment]
I recommend to use scaler like this: http://www.aliexpress.com/item/Hot-New-HDMI-and-SCART-to-HDMI-1080P-720-HD-Video-Adapter-Converter/2043816844.html
It supports original retro modes.
