### ISSUE TITLE
TRDs created with scl2trd don't work

### ISSUE THREAD

**Issue by jamesrc** [sorgelig/ZX_Spectrum-128K_MIST#6]
I'm unable to read any TRD file that I create with Fuse's scl2trd utility on the MiST using the Spectrum core.

If I go to TR-DOS and try to CAT the disk, it hangs forever.

I've tried this with multiple images, for example: http://trd.speccy.cz/gamez/d/DDAR_POS.ZIP

The same TRD file works correctly in the Fuse emulator.

**Comment by sorgelig** [comment]
Try today's release

**Comment by jamesrc** [comment]
Thanks for looking at this.  Sadly, I'm still seeing the same behaviour.

**Comment by Blackbaud-JamesCurry** [comment]
(Just to be clear -- the link I've provided is to a SCL file.  I'm running scl2trd to produce a TRD file which works fine under an emulator, but not on the MiST board.  You probably already knew this, but reading back I felt my original message might have lacked clarity).

**Comment by jamesrc** [comment]
(Just to be clear -- the link I've provided is to a SCL file. I'm running scl2trd to produce a TRD file which works fine under an emulator, but not on the MiST board. You probably already knew this, but reading back I felt my original message might have lacked clarity).

**Comment by sorgelig** [comment]
Probably, your converter is not fully compatible with basic TRD structure. Fuse emulator may support more advanced and extended format inside TRD and thus works, while MiST supports only plain basic format and probably it's not true after your converter.

i'm using console trx2x.exe utility to convert from SCL to TRD. And it works in my ZX core.

**Comment by sorgelig** [comment]
https://mega.nz/#!lF4yyTiT!IBoBWG7cUhLaVvxCNQMt8Mu7UEcrS5nQc-0yAw5CZQQ

**Comment by jamesrc** [comment]
I converted the file again with the tool you provided, and have the exact same result.  I have a trd file that I can mount in the Fuse emulator, go to TR-DOS, type the "CAT" keyword and see the contents of, but which causes the Spectrum to hang when I try the same thing on the MiST.

Here is the TRD file, in case you would like to inspect it:

https://mega.nz/#!gyIEyCJB!hQEXxp0FOYBJUTBGMKnT-e6rj74AjdJUhpS1BZgSBhs

**Comment by sorgelig** [comment]
actually I use LIST command instead of CAT. 
Just tried CAT - it hangs. I have no idea why it happens. Is it necessary to use exactly CAT?

**Comment by jamesrc** [comment]
Huh.  Well, sorry, I really should have tried that.  Using CAT is just force of habit from owning a Microdrive.

Yep, it works for me with LIST on every image I tried.

That's certain odd and I'd be curious to know why it happens, but you've solved my immediate problem.  So, thank you!
